### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by PaulSoderlind** [panlanfeng/KernelEstimator.jl#2]
Hi,

on Julia 0.4.5 (Windows 7, 64bit), Pkg.add("KernelEstimator") generates lots of error messages when trying to install Cubature. 

However, this works: first install Cubature, then Yeppp and finally KernelEstimator.

Btw. the Require file says "julia 0.3." Wrong?

/Paul S

**Comment by panlanfeng** [comment]
Could you run 
~~~julia
Pkg.build("Cubature")
~~~
and see if there is any error?

This package itself can work both on julia 0.3 and 0.4. "Julia 0.3" means 0.3 and above.

**Comment by PaulSoderlind** [comment]
Hi again,
I tried on two other machines. In these cases, Pkg.add("KernelEstimator") seems to work. However, at "using KernelEstimator" the pre-compile fails because of problems with Yeppp. Running Pkg.build("Yeppp") starts a download from/to a Yeppp-1.0.0\bindings folder. After that all works well.

Btw. could you add some more documentation on eg. the cross validation? Are you using an EPE as the loss function? My experience with EPE has led me to loop over different bandwitdths and then inspect the loss function graphically (non-monotic).

**Comment by panlanfeng** [comment]
Your previous problem with Cubature.jl is most likely a bug of Cubature or BinDeps.
I will make a fix of the precompile issue soon. Currently you can get around that by restarting Julia and then you will be fine.

All the cross validation uses leave one out mean squared error, which can be found in most textbook or lecture notes about nonparametric, such as here http://www.ssc.wisc.edu/~bhansen/718/NonParametrics1.pdf
In some cases cross validation does give bad bandwidth however there is no better alternatives. It is commonly  acceptable to adjust the bandwidth by a little bit if it gives a too small bandwidth.

I am not sure what EPE means.

**Comment by PaulSoderlind** [comment]
Hi,

thanks.

 >uses leave one out mean squared erro
that's what I meant by EPE, see eq 6.12 of the attached notes. See also 
Fig 6.6 for a result from looping over different bandwitdhs (in this 
case, it's well-behaved).

Thanks for providing the code.

/Paul S

**Comment by panlanfeng** [comment]
Oops, I cannot see any attachment. 
If you replied this via email, an attachment will be removed by Github.
You can send me email at pan@iastate.edu if you like.

**Comment by panlanfeng** [comment]
This should have been fixed since Cubature being updated.
